/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthProfileRouteImport } from './routes/health-profile'
import { Route as DoctorApprovalRouteImport } from './routes/doctor-approval'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const HealthProfileRoute = HealthProfileRouteImport.update({
  id: '/health-profile',
  path: '/health-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorApprovalRoute = DoctorApprovalRouteImport.update({
  id: '/doctor-approval',
  path: '/doctor-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/doctor-approval': typeof DoctorApprovalRoute
  '/health-profile': typeof HealthProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/doctor-approval': typeof DoctorApprovalRoute
  '/health-profile': typeof HealthProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/doctor-approval': typeof DoctorApprovalRoute
  '/health-profile': typeof HealthProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/doctor-approval' | '/health-profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/doctor-approval' | '/health-profile'
  id: '__root__' | '/' | '/dashboard' | '/doctor-approval' | '/health-profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DoctorApprovalRoute: typeof DoctorApprovalRoute
  HealthProfileRoute: typeof HealthProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health-profile': {
      id: '/health-profile'
      path: '/health-profile'
      fullPath: '/health-profile'
      preLoaderRoute: typeof HealthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-approval': {
      id: '/doctor-approval'
      path: '/doctor-approval'
      fullPath: '/doctor-approval'
      preLoaderRoute: typeof DoctorApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DoctorApprovalRoute: DoctorApprovalRoute,
  HealthProfileRoute: HealthProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
